api:
  url: http://surveyor-api.dev/

steps:
  - location
  - bearing-introduction
  - bearing
  - thanks

search_buttons:
  - title: NYPL Digital Collections
    url: http://digitalcollections.nypl.org/items/{uuid}

  - title: Google
    url: https://www.google.com/search?q={title}

  - title: Wikipedia
    url: https://en.wikipedia.org/wiki/Special:Search?search={title}

  - title: Map Warper
    url: http://maps.nypl.org/warper/maps?field=text&query={title}

css_variables:
  # mainColor: red
  # altColor: blue
  mobileWidth: 800px
  textColor: ''
  linkColor: '#d0343a'
  headerBackground: ''
  appBackground: ''
  sidebarBackground: ''

defaults:
  map:
    # grayscale: true
    # tileUrl: http://otile{s}.mqcdn.com/tiles/1.0.0/osm/{z}/{x}/{y}.png
    # subdomains: 1234
    # attribution: 'Tiles &copy; <a href="http://www.mapquest.com/" target="_blank">MapQuest</a> <img src="http://developer.mapquest.com/content/osm/mq_logo.png" />'
    tileUrl: http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png
    subdomains: abcd
    attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, &copy; <a href="http://cartodb.com/attributions">CartoDB</a>'
    # scrollWheelZoom: false
    scrollWheelZoom: center
    doubleClickZoom: center
    center: [40.75319,-73.98224]
    zoom: 10
    maxZoom: 18
